name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: php syntax checking
      run: find . -type f | egrep  "[^/]*\.php" | xargs -n1 php -l

